# A list of SPDX license identifiers separated by `OR` or `AND`
# See https://spdx.org/licenses/ for a full list
#
# Licenses are in "priority" order, so if a crate is dual-licensed with
# `Apache-2.0 OR MIT` then `Apache-2.0` will be chosen as it is first
# in the list.
accepted = [
    "Apache-2.0",
    "MIT",
    "ISC",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "MPL-2.0",
    "Unicode-3.0",
    "Unlicense",
    "Apache-2.0 WITH LLVM-exception",
] 
