name: Build and Upload to Google Drive

on:
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ${{ matrix.settings.platform }}

    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: macos-14
            artifact-name: document-encoder-macos
            build-path: "src-tauri/target/release/bundle/dmg"
            file-pattern: "*.dmg"
            upload-name: "DocumentEncoder-macOS"
          - platform: windows-latest
            artifact-name: document-encoder-windows
            build-path: "src-tauri/target/release/bundle/msi"
            file-pattern: "*.msi"
            upload-name: "DocumentEncoder-Windows"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app
        run: npm run tauri build

      - name: Create timestamp
        id: timestamp
        run: echo "timestamp=$(date +%Y-%m-%d-%H-%M-%S)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Find and prepare artifact
        id: find-artifact
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ARTIFACT_PATH=$(find "${{ matrix.settings.build-path }}" -name "${{ matrix.settings.file-pattern }}" -type f | head -1)
            EXT=".msi"
          else
            ARTIFACT_PATH=$(find "${{ matrix.settings.build-path }}" -name "${{ matrix.settings.file-pattern }}" -type f | head -1)
            EXT=".dmg"
          fi

          if [[ -z "$ARTIFACT_PATH" ]]; then
            echo "Error: No artifact found in ${{ matrix.settings.build-path }}"
            exit 1
          fi

          FILENAME="${{ matrix.settings.upload-name }}-${{ steps.timestamp.outputs.timestamp }}${EXT}"
          echo "artifact-path=$ARTIFACT_PATH" >> $GITHUB_OUTPUT
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
          echo "Found artifact: $ARTIFACT_PATH"
          echo "Upload filename: $FILENAME"

      - name: Upload to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          target: ${{ steps.find-artifact.outputs.artifact-path }}
          folder: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          name: ${{ steps.find-artifact.outputs.filename }}

      - name: Upload build artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.settings.artifact-name }}-${{ steps.timestamp.outputs.timestamp }}
          path: ${{ steps.find-artifact.outputs.artifact-path }}
          retention-days: 30
