name: Build and Upload to Google Drive

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  build-and-upload:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop')
    runs-on: ${{ matrix.settings.platform }}

    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: macos-latest
            artifact-name: document-encoder-macos
            upload-name: DocumentEncoder-macOS-${{ github.event.head_commit.timestamp }}.dmg
          - platform: windows-latest
            artifact-name: document-encoder-windows
            upload-name: DocumentEncoder-Windows-${{ github.event.head_commit.timestamp }}.msi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          args: ""

      - name: Find built artifact (macOS)
        if: matrix.settings.platform == 'macos-latest'
        id: find-artifact-macos
        run: |
          ARTIFACT_PATH=$(find src-tauri/target/release/bundle/dmg -name "*.dmg" | head -1)
          echo "artifact-path=$ARTIFACT_PATH" >> $GITHUB_OUTPUT
          echo "Found artifact: $ARTIFACT_PATH"

      - name: Find built artifact (Windows)
        if: matrix.settings.platform == 'windows-latest'
        id: find-artifact-windows
        shell: powershell
        run: |
          $ArtifactPath = Get-ChildItem -Path "src-tauri/target/release/bundle/msi" -Filter "*.msi" | Select-Object -First 1 -ExpandProperty FullName
          echo "artifact-path=$ArtifactPath" >> $env:GITHUB_OUTPUT
          echo "Found artifact: $ArtifactPath"

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          filename: ${{ steps.find-artifact-macos.outputs.artifact-path || steps.find-artifact-windows.outputs.artifact-path }}
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          name: ${{ matrix.settings.upload-name }}
          overwrite: "true"

      - name: Upload build artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.settings.artifact-name }}
          path: ${{ steps.find-artifact-macos.outputs.artifact-path || steps.find-artifact-windows.outputs.artifact-path }}
          retention-days: 30
